replicaCount: 1

image:
  repository: docker.io/orik45/weather-backend-server
  tag: dev
  pullPolicy: IfNotPresent
  containerPort: 5000

service:
  type: ClusterIP
  port: 5000

env:
  SKYCAST_ENV: dev
